### ISSUE TITLE
Switching the Theme Doesn’t Work

### ISSUE THREAD

**Issue by burkybang** [qwertyuiop1379/AnActuallyGoodFilzaEditor#1]
Here’s a video of the issue:

https://imgur.com/a/EYJDinp

**Comment by qwertyuiop1379** [comment]
This will he fixed soon, hopefully tonight

**Comment by burkybang** [comment]
No prob. Take your time 🙂

**Comment by burkybang** [comment]
It works now. Thanks!

**Comment by absidue** [comment]
It is still won't save the changes when the property list file at `/var/mobile/Library/Preferences/com.qiop1379.anactuallygoodfilzaeditor.plist` doesn't exist. I had to manually create the file before it would change the theme.

**Comment by qwertyuiop1379** [comment]
@absidue the issue was fixed in the most recent version

**Comment by absidue** [comment]
@qwertyuiop1379 Sorry for the inconvenience, I just checked and I was still using your old repo ☹️. Now I have the issue that the text is black in any plaintext file until I select a language, which is an issue with the dark themes.

**Comment by qwertyuiop1379** [comment]
Weird I thought I fixed that too. I'll look into it when I can
